{
 "title": "Trafico Tiempo Real",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "MITIGATED",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "/* grafana dashboard='Trafico Tiempo Real', user=1 */\nSELECT *\r\nFROM default.mitigation_actions\r\nWHERE created_at >= now() - INTERVAL 1 HOUR\r\n  AND status IN ('applied', 'mitigated')\r\nORDER BY created_at DESC",
     "query": "SELECT *\r\nFROM default.mitigation_actions\r\nWHERE created_at >= now() - INTERVAL 1 HOUR\r\n  AND status IN ('applied', 'mitigated')\r\nORDER BY created_at DESC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "TCP PPPs",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "/* grafana dashboard='Trafico Tiempo Real', user=1 */\nSELECT\r\n  max(tcp_pps) AS max_tcp_pps\r\nFROM\r\n(\r\n  SELECT\r\n    sumMerge(tcp_packets_state) / 10 AS tcp_pps\r\n  FROM default.flow_metrics_10s\r\n  WHERE window_start >= now() - INTERVAL 15 MINUTE\r\n  GROUP BY window_start\r\n)",
     "query": "SELECT\r\n  max(tcp_pps) AS max_tcp_pps\r\nFROM\r\n(\r\n  SELECT\r\n    sumMerge(tcp_packets_state) / 10 AS tcp_pps\r\n  FROM default.flow_metrics_10s\r\n  WHERE window_start >= now() - INTERVAL 15 MINUTE\r\n  GROUP BY window_start\r\n)\r\n",
     "round": "0s"
    }
   ]
  },
  {
   "title": "UDP PPPs",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "/* grafana dashboard='Trafico Tiempo Real', user=1 */\nSELECT\r\n  max(udp_pps) AS max_udp_pps\r\nFROM\r\n(\r\n  SELECT\r\n    sumMerge(udp_packets_state) / 10 AS udp_pps\r\n  FROM default.flow_metrics_10s\r\n  WHERE window_start >= now() - INTERVAL 15 MINUTE\r\n  GROUP BY window_start\r\n)",
     "query": "SELECT\r\n  max(udp_pps) AS max_udp_pps\r\nFROM\r\n(\r\n  SELECT\r\n    sumMerge(udp_packets_state) / 10 AS udp_pps\r\n  FROM default.flow_metrics_10s\r\n  WHERE window_start >= now() - INTERVAL 15 MINUTE\r\n  GROUP BY window_start\r\n)\r\n",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Ancho de Banda -Live  – bits por Segundo",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Mb/s" } },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "/* grafana dashboard='Trafico Tiempo Real', user=1 */\nSELECT\r\n  toUnixTimestamp(window_start) * 1000 AS time,\r\n  (sumMerge(total_bytes_state) * 8) / 10 / 1000000 AS mbps\r\nFROM default.flow_metrics_10s\r\nWHERE\r\n  window_start >= toDateTime(intDiv(1770904814086, 1000))\r\n  AND window_start <= toDateTime(intDiv(1770905714086, 1000))\r\nGROUP BY window_start\r\nORDER BY window_start",
     "query": "SELECT\r\n  toUnixTimestamp(window_start) * 1000 AS time,\r\n  (sumMerge(total_bytes_state) * 8) / 10 / 1000000 AS mbps\r\nFROM default.flow_metrics_10s\r\nWHERE\r\n  window_start >= toDateTime(intDiv($__from, 1000))\r\n  AND window_start <= toDateTime(intDiv($__to, 1000))\r\nGROUP BY window_start\r\nORDER BY window_start\r\n",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Live Traffic – Paquetes Por Segundo (10s window)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "/* grafana dashboard='Trafico Tiempo Real', user=1 */\nSELECT\r\n  toUnixTimestamp(window_start) * 1000 AS time,\r\n  sumMerge(tcp_packets_state) / 10 AS tcp,\r\n  sumMerge(udp_packets_state) / 10 AS udp,\r\n  sumMerge(icmp_packets_state) / 10 AS icmp\r\nFROM default.flow_metrics_10s\r\nWHERE\r\n  window_start >= toDateTime(intDiv(1771100821397, 1000))\r\n  AND window_start <= toDateTime(intDiv(1771101721397, 1000))\r\nGROUP BY window_start\r\nORDER BY window_start",
     "query": "SELECT\r\n  toUnixTimestamp(window_start) * 1000 AS time,\r\n  sumMerge(tcp_packets_state) / 10 AS tcp,\r\n  sumMerge(udp_packets_state) / 10 AS udp,\r\n  sumMerge(icmp_packets_state) / 10 AS icmp\r\nFROM default.flow_metrics_10s\r\nWHERE\r\n  window_start >= toDateTime(intDiv($__from, 1000))\r\n  AND window_start <= toDateTime(intDiv($__to, 1000))\r\nGROUP BY window_start\r\nORDER BY window_start\r\n",
     "round": "0s"
    }
   ]
  },
  {
   "title": "TOP 10 SRC_IP (15m)",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "/* grafana dashboard='Trafico Tiempo Real', user=1 */\nSELECT *\r\nFROM default.v_top_src_pps",
     "query": "SELECT *\r\nFROM default.v_top_src_pps\r\n",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Flows Por Segundo (10s window)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "flows/s" } },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "/* grafana dashboard='Trafico Tiempo Real', user=1 */\nSELECT\r\n  toUnixTimestamp(window_start) * 1000 AS time,\r\n  countMerge(total_flows_state) / 10 AS flows_per_second\r\nFROM default.flow_metrics_10s\r\nWHERE\r\n  window_start >= toDateTime(intDiv(1770932813088, 1000))\r\n  AND window_start <= toDateTime(intDiv(1770933713088, 1000))\r\nGROUP BY window_start\r\nORDER BY window_start",
     "query": "SELECT\r\n  toUnixTimestamp(window_start) * 1000 AS time,\r\n  countMerge(total_flows_state) / 10 AS flows_per_second\r\nFROM default.flow_metrics_10s\r\nWHERE\r\n  window_start >= toDateTime(intDiv($__from, 1000))\r\n  AND window_start <= toDateTime(intDiv($__to, 1000))\r\nGROUP BY window_start\r\nORDER BY window_start\r\n",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Packets per Flow Ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "/* grafana dashboard='Trafico Tiempo Real', user=1 */\nSELECT\r\n  toUnixTimestamp(window_start) * 1000 AS time,\r\n  (\r\n    sumMerge(total_packets_state)\r\n    /\r\n    nullIf(countMerge(total_flows_state), 0)\r\n  ) AS packets_per_flow\r\nFROM default.flow_metrics_10s\r\nWHERE\r\n  window_start >= toDateTime(intDiv(1770933765014, 1000))\r\n  AND window_start <= toDateTime(intDiv(1770934665014, 1000))\r\nGROUP BY window_start\r\nORDER BY window_start",
     "query": "SELECT\r\n  toUnixTimestamp(window_start) * 1000 AS time,\r\n  (\r\n    sumMerge(total_packets_state)\r\n    /\r\n    nullIf(countMerge(total_flows_state), 0)\r\n  ) AS packets_per_flow\r\nFROM default.flow_metrics_10s\r\nWHERE\r\n  window_start >= toDateTime(intDiv($__from, 1000))\r\n  AND window_start <= toDateTime(intDiv($__to, 1000))\r\nGROUP BY window_start\r\nORDER BY window_start\r\n",
     "round": "0s"
    }
   ]
  }
 ]
}